// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhasFinancas.Domain;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinhasFinancas.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230602141335_adicionandoRegraNaTabelaAccount")]
    partial class adicionandoRegraNaTabelaAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinhasFinancas.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount_received_per_month")
                        .HasColumnType("double precision");

                    b.Property<double>("Available_value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime?>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("Responsible_user")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("User_created")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("User_updated")
                        .HasColumnType("uuid");

                    b.Property<double>("Value_credit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.HasKey("Id");

                    b.HasIndex("Responsible_user");

                    b.HasIndex("User_created");

                    b.HasIndex("User_updated");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("Account_activated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool?>("Activated_by_email")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("User_created")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("User_updated")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("User_created");

                    b.HasIndex("User_updated");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.Account", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.User", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("Responsible_user");

                    b.HasOne("MinhasFinancas.Domain.User", "UserCreated")
                        .WithMany()
                        .HasForeignKey("User_created");

                    b.HasOne("MinhasFinancas.Domain.User", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("User_updated");

                    b.Navigation("ResponsibleUser");

                    b.Navigation("UserCreated");

                    b.Navigation("UserUpdated");
                });

            modelBuilder.Entity("MinhasFinancas.Domain.User", b =>
                {
                    b.HasOne("MinhasFinancas.Domain.User", "UserCreated")
                        .WithMany()
                        .HasForeignKey("User_created");

                    b.HasOne("MinhasFinancas.Domain.User", "UserUpdated")
                        .WithMany()
                        .HasForeignKey("User_updated");

                    b.Navigation("UserCreated");

                    b.Navigation("UserUpdated");
                });
#pragma warning restore 612, 618
        }
    }
}
